name: Delete All Tags

on:
  workflow_dispatch:  # Triggered manually
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  delete-all-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Delete all tags
        run: |
          # Get all tags
          tags=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               "https://api.github.com/repos/${{ github.repository }}/git/refs/tags" \
               | jq -r '.[].ref' | sed 's|refs/tags/||')
          
          # Iterate over and delete each tag
          for tag in $tags
          do
            curl -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 "https://api.github.com/repos/${{ github.repository }}/git/refs/tags/$tag"
            echo "Deleted tag: $tag"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
