name: Delete All Releases

on:
  workflow_dispatch:  # Triggered manually
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  delete-releases:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List and delete all releases (with pagination)
        run: |
          # Initialize page number and release ID list
          page=1
          releases=""

          # Get release IDs from all pages of releases
          while true; do
            result=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases?per_page=100&page=$page" | jq -r '.[].id')

            if [ -z "$result" ]; then
              break
            fi

            releases="$releases $result"
            page=$((page + 1))
          done

          # Check if there are releases
          if [ -z "$releases" ]; then
            echo "No releases found."
            exit 0
          fi

          # Delete each release
          for id in $releases; do
            echo "Deleting release ID: $id"
            curl -s -X DELETE -H "Authorization: token ${{ secrets.TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/$id"
          done

          echo "All releases deleted."
