name: Generate AdBlock IPV6 Host List

# Trigger conditions
on:
  schedule:
    - cron: '*/20 * * * *'  # Runs every 20 minutes
  workflow_dispatch:  # Supports manual triggering

jobs:
  filter-rules:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Use the latest Python 3 version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytz  # Install pytz library to handle time zones

      # Step 4: Process AdBlock rules
      - name: Process AdBlock rules
        run: |
          python3 << EOF
          import datetime
          import pytz
          import re

          # DNS domain validation regex that conforms to DNS standards
          dns_domain_regex = re.compile(
              r'^(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\.[A-Za-z0-9-]{1,63})*\.[A-Za-z]{2,}$'
          )

          def process_file(input_file, output_file, title):
              with open(input_file, 'r', encoding='utf-8') as f:
                  rules = []
                  for line in f:
                      line = line.strip()
                      match = re.match(r'^\|\|([a-zA-Z0-9.-]+)\^$', line)
                      if match:
                          domain = match.group(1)
                          if not re.match(r'^\d+\.\d+\.\d+\.\d+$', domain) and dns_domain_regex.match(domain):
                              rules.append(f":: {domain}")
              
              tz = pytz.timezone('Asia/Shanghai')
              timestamp = datetime.datetime.now(tz).strftime('%Y-%m-%d %H:%M:%S')
              
              header = f"""
          #Title: {title}
          #Description: A host file summarizing multiple ad filter rules, updated every 20 minutes to ensure timely synchronization with upstream filters and reduce false positives.
          #Homepage: https://github.com/TheEndBoss-101-Web/ips
          #LICENSE1: https://github.com/TheEndBoss-101-Web/ips/blob/main/LICENSE-GPL 3.0
          #LICENSE2: https://github.com/TheEndBoss-101-Web/ips/blob/main/LICENSE-CC-BY-NC-SA 4.0
          #This code is based on https://github.com/REIJI007/Adblock-Rule-Collection/
          #Generation Time: {timestamp}
          #Valid Rule Count: {len(rules)}
          """
              
              with open(output_file, 'w', encoding='utf-8') as f:
                  f.write(header + '\n')
                  f.write('\n'.join(rules) + '\n')
              
              print(f"Processed {input_file}. Total rules: {len(rules)}")

          process_file('ADBLOCK_RULE_COLLECTION.txt', 'ADBLOCK_RULE_COLLECTION_HOST_IPV6.txt', 'Adblock-Rule-Collection-Host-IPv6')
          EOF

      # Step 5: Commit and push changes
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git add -A  # Add all changes
          
          attempt=0
          max_attempts=5
          success=false

          git fetch origin main  
          git merge origin/main --strategy-option=ours || git merge --abort || echo "Merge conflicts resolved automatically using 'ours' strategy."

          while [ $attempt -lt $max_attempts ]; do
              git commit -m "Update AdBlock Host Rules with IPv6 format" && success=true && break
              attempt=$((attempt + 1))
              echo "Commit failed, retrying in 10 seconds... (Attempt $attempt of $max_attempts)"
              sleep 10
          done
          
          if [ "$success" = true ]; then
              attempt=0
              success=false
              while [ $attempt -lt $max_attempts ]; do
                  git push origin main && success=true && break
                  attempt=$((attempt + 1))
                  echo "Push failed, retrying in 10 seconds... (Attempt $attempt of $max_attempts)"
                  sleep 10
              done
              
              if [ "$success" = false ]; then
                  echo "Push failed after $max_attempts attempts. Continuing workflow."
              else:
                  echo "Push successful."
              fi
          else
              echo "Commit failed after $max_attempts attempts. Continuing workflow."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
