name: Release Adblock File  # Workflow name

on:
  schedule:
    - cron: '*/20 * * * *'  # Run every 20 minutes
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  create-release:
    runs-on: ubuntu-latest  # Use the latest Ubuntu version as the runtime environment

    steps:
      - name: Clear previous logs  # Clear previous log files
        run: |
          sudo rm -rf /home/runner/runners/*/_diag/*.log || true
    
      - name: Checkout code  # Checkout the code
        uses: actions/checkout@v3  # Use the official checkout action to fetch the repository code

      - name: Get current time  # Get the current time
        id: current-time  # Set step ID for future references
        run: echo "time=$(date +'%y%m%d%H%M')" >> $GITHUB_ENV  # Get the current time and store it as a GitHub Actions environment variable

      - name: Update timestamp file  # Update the timestamp file
        run: echo "${{ env.time }}" > timestamp.txt  # Write the current time to timestamp.txt

      - name: Force add and commit changes  # Force add and commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -f ADBLOCK_RULE_COLLECTION.txt ADBLOCK_RULE_COLLECTION_Lite.txt ADBLOCK_RULE_COLLECTION_HOST.txt ADBLOCK_RULE_COLLECTION_HOST_Lite.txt ADBLOCK_RULE_COLLECTION_DNS.txt ADBLOCK_RULE_COLLECTION_DNS_Lite.txt ADBLOCK_RULE_COLLECTION_HOST_IPV6.txt ADBLOCK_RULE_COLLECTION_HOST_IPV6_Lite.txt ADBLOCK_RULE_COLLECTION_DOMAIN.txt ADBLOCK_RULE_COLLECTION_DOMAIN_Lite.txt timestamp.txt
          git commit -m "Forced update of adblock files and timestamp"
          for attempt in {1..5}; do  # Try 5 times
            if git push origin main; then
              break
            else
              echo "Push failed, attempting to pull and rebase..."
              git pull --rebase  # Pull and rebase changes from remote
              sleep $((attempt * 10))  # Exponential backoff, wait 10 seconds on first attempt, 20 seconds on second, and so on
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use custom token for authentication

      - name: Create Release  # Create a new release
        id: create_release  # Set step ID for future references
        uses: actions/create-release@v1  # Use the official create-release action
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use custom token for authentication
        with:
          tag_name: release-${{ env.time }}  # Use current time as the tag name
          release_name: Release ${{ env.time }}  # Use current time as the release name
          body: "Periodic release of adblock files."  # Release description
          draft: false  # Publish as a final release
          prerelease: false  # Do not publish as a pre-release

      - name: Upload ADBLOCK_RULE_COLLECTION.txt  # Upload ADBLOCK_RULE_COLLECTION.txt file
        uses: actions/upload-release-asset@v1  # Use the official upload-release-asset action
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use custom token for authentication
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Use the upload URL from the release creation step
          asset_path: ADBLOCK_RULE_COLLECTION.txt  # File path to upload
          asset_name: ADBLOCK_RULE_COLLECTION.txt  # Name of the file after upload
          asset_content_type: text/plain  # File content type

      - name: Upload ADBLOCK_RULE_COLLECTION_HOST.txt  # Upload ADBLOCK_RULE_COLLECTION_HOST.txt file
        uses: actions/upload-release-asset@v1  # Use the official upload-release-asset action
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use custom token for authentication
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Use the upload URL from the release creation step
          asset_path: ADBLOCK_RULE_COLLECTION_HOST.txt  # File path to upload
          asset_name: ADBLOCK_RULE_COLLECTION_HOST.txt  # Name of the file after upload
          asset_content_type: text/plain  # File content type

      - name: Upload ADBLOCK_RULE_COLLECTION_DNS.txt  # Upload ADBLOCK_RULE_COLLECTION_DNS.txt file
        uses: actions/upload-release-asset@v1  # Use the official upload-release-asset action
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use custom token for authentication
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Use the upload URL from the release creation step
          asset_path: ADBLOCK_RULE_COLLECTION_DNS.txt  # File path to upload
          asset_name: ADBLOCK_RULE_COLLECTION_DNS.txt  # Name of the file after upload
          asset_content_type: text/plain  # File content type

      - name: Upload ADBLOCK_RULE_COLLECTION_HOST_IPV6.txt  # Upload ADBLOCK_RULE_COLLECTION_HOST_IPV6.txt file
        uses: actions/upload-release-asset@v1  # Use the official upload-release-asset action
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use custom token for authentication
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Use the upload URL from the release creation step
          asset_path: ADBLOCK_RULE_COLLECTION_HOST_IPV6.txt  # File path to upload
          asset_name: ADBLOCK_RULE_COLLECTION_HOST_IPV6.txt  # Name of the file after upload
          asset_content_type: text/plain  # File content type

      - name: Upload ADBLOCK_RULE_COLLECTION_DOMAIN.txt  # Upload ADBLOCK_RULE_COLLECTION_DOMAIN.txt file
        uses: actions/upload-release-asset@v1  # Use the official upload-release-asset action
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}  # Use custom token for authentication
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}  # Use the upload URL from the release creation step
          asset_path: ADBLOCK_RULE_COLLECTION_DOMAIN.txt  # File path to upload
          asset_name: ADBLOCK_RULE_COLLECTION_DOMAIN.txt  # Name of the file after upload
          asset_content_type: text/plain  # File content type